### ISSUE TITLE
Quiet reporting mode

### ISSUE THREAD

**Issue by Kylaaa** [Roblox/testez#40] opened 2019-04-20 01:07 UTC
As test suites get larger, it would be nice to be able configure the TestBootstrap to only print out the tests that have failed.

Then you can see your output as simple as :
Test results:
[-] Components
--[-] Foo
----[-] should create and destroy without errors
--[-] Batz
----[-] should handle this obscure case
[-] Utils
--[-] createGrobular
----[-] should create a new and functioning Grobular
86 passed, 2 failed, 10 skipped
2 test nodes reported failures.
Errors reported by tests: .....

**Comment by AmaranthineCodices** [comment] 2019-04-20 01:21
Duplicate of #17.

**Closed by AmaranthineCodices** 2019-04-20 01:21 UTC

**Comment by LPGhatguy** [comment] 2019-04-20 23:16
This has also already been fixed (which means #17 has been too) with `TextReporterQuiet`, I'd think?
